version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=12341234
      - MYSQL_PASSWORD=12341234
      - MYSQL_DATABASE=users
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8098:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/users?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "12341234"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone